config/routes.rb
Rails.application.routes.draw do



  resources :articles
  root  'articles#home'
  get 'welcome/about', to: 'welcome#about'

  #sign-up
  resources :users, except: [:new]
  get 'signup', to: 'users#new'
  post 'users', to:'users#create'
  get  'login', to: 'seassions#new'
  post 'login' ,to: 'seassions#create'
  delete 'logout' ,to: 'seassions#destroy'
  get  'logout', to: 'seassions#destroy'

  resources :categories

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/User.rb
class User < ApplicationRecord
  # set the relation
has_many :articles, dependent: :destroy
# before data save in database ensure
before_save{self.email =  email.downcase }
  # to save data plz validate
  validates :username, presence:true , length:{minimum:1,maximum:10},uniqueness:{case_sensitive:false}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email , presence:true, uniqueness:{case_sensitive:false}, format:{ with: VALID_EMAIL_REGEX}

  #secure password
  has_secure_password


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

  has_many :article_categories
  has_many :categories, through: :article_categories
  
  belongs_to :user

  validates :title, presence: true,length: {minimum:3,maximum:40}
  validates :description, presence: true , length: {minimum:10,maximum:200000}

end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord

has_many :article_categories
has_many :articles, through: :article_categories

  validates :name, presence: true
  validates :name, uniqueness: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


      def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
      end

      def logged_in
        !!current_user
      end

      def require_user
        if !logged_in
          flash[:danger] = "you are not logged in, Sir/Madam"
          redirect_to root_path
        end
      end
      def is_admin
       if logged_in && current_user.admin?
       end

  end



      # don't forget this line too
      helper_method :current_user,:logged_in,:require_user,:is_admin
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :destroy, :update, :show]
  before_action :require_user, only:[:edit, :destroy,:update, :create]
  before_action :require_same_user, only:[:edit, :destroy, :update]




def home

  redirect_to articles_path if logged_in
end


def index
  @articles =  Article.paginate(page: params[:page], per_page: 5)
end

def new
  @article = Article.new
end

def create
  @article = Article.new(article_params)
  @article.user = current_user
  if @article.save
    flash[:success] = "thank you, your article is saved"
    redirect_to article_path(@article)
  else
    render 'new'
  end
end

def show
  
end

def edit

end

def update

  if @article.update(article_params)
    redirect_to article_path(@article)
  else
    render 'edit'
  end
end
  def destroy
    @article.destroy
    redirect_to articles_path
    flash[:success] = "article has been deleted"

  end

def article_params
  params.require(:article).permit(:title , :description,category_ids:[])
end
def set_article
  @article = Article.find(params[:id])
end

def require_same_user
  if current_user != @article.user and !current_user.admin?
    flash[:danger] = "sorry this is not your ID "
    redirect_to root_path
end
end


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController


before_action :set_category,only:[:show,:edit,:destroy,:update]
before_action :require_admin, only:[:new,:create,:destroy,:update,:edit]

def index
  @categories = Category.paginate(page: params[:page], per_page: 5)
end

def new
  @category = Category.new
end

def create
  @category  = Category.new(all_params)
    @category .save
    redirect_to categories_path
end

def show
  @category = Category.find(params[:id])
  @article_categories = @category.articles.paginate(page: params[:page], per_page:4)
end

def edit

end
def update
  if @category.update(all_params)
    redirect_to category_path(@category)
  else
    render 'edit'
  end
end

def destroy
end

private

def all_params
  params.require(:category).permit(:name)
end
def set_category
  @category = Category.find(params[:id])
end


private
def require_admin
  if !logged_in || (logged_in and !current_user.admin?)
    flash[:danger] = "you arent allowed to access this page"
    redirect_to categories_path

  end
end
end

app/controllers/seassions_controller.rb
class SeassionsController < ApplicationController

  def new
    if session[:user_id] != nil
    redirect_to root_path
  end
  end

  def create
# find the user, by email compared to param[:seassion][:email]
    user = User.find_by(email: params[:seassion][:email])
    # if user exists then auth by user,auth(params[seassion and password])
    if user && user.authenticate(params[:seassion][:password])
      #save the id in seassion if user exists
      session[:user_id] = user.id
      flash[:success]= "you have logged in"
      redirect_to user_path(user)
    else

      flash.now[:danger] = "wrong data"
      render 'new'

    end
  end

  def destroy
  session[:user_id] = nil
  flash[:success] = "you are logout"
  render 'new'

  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

before_action :set_user ,only:[:edit,:update,:show,:distroy]
before_action :require_same_user , only:[:edit, :update,:distroy]

def index
  @users = User.all
end

def new
  @user = User.new
end

def create
  @user = User.new(user_params)
  if @user.save
    session[:user_id] = @user.id
    flash[:success] = "welcome to mytest#{@user.username}"
    redirect_to user_path(@user)
  else
    render 'new'

  end
end

def login
  flash[:success] = "user logged in"
end

def edit
end

def update
  if @user.update(user_params)
   flash[:success] = "your info has been updated"
   redirect_to articles_path
  else

    render 'edit'

  end
end


def show
end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
    flash[:success] = "user has been deleted"

  end


def set_user
  @user = User.find(params[:id])
end

def user_params
  params.require(:user).permit(:username,:email,:password)
end

def require_same_user
    if current_user != @user and !current_user.admin?
    flash[:danger] = "not allowed for this action"
    redirect_to root_path

  end
end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
def home

end
def about 
end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(user, size)
  gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
  "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
end
end

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj:@article %>


<div class="row">
  <div class="col-xs-12">
<%= form_for(@article, html: {class: "form-horizontal", role:'form'}) do |a| %>
<div class="form-group">
  <label class="col-sm-2 control-label">Title</label>
    <div class="col-sm-8">
        <%= a.text_field :title , class: "form-control", placeholder: 'title here' %>
    </div>
</div>
  <div class="form-group">
    <label class="col-sm-2 control-label">Description</label>
      <div class="col-sm-8">
          <%= a.text_area :description, rows: 10 ,class: "form-control", placeholder: 'enter the description' %>
      </div>
 </div>
 <div class="form-group">
     <div class="col-sm-offset-2 col-sm-10">
       <%= a.collection_check_boxes(:category_ids, Category.all, :id, :name)do |b| %>
       <%= b.check_box(class:"checkbox-inline") + b.text%>
<% end %>
     </div> 
 </div>
      <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <%= a.submit :submit , class: "btn btn-primary btn-lg" %>
          </div>
      </div>
<%end%>
</div>

</div>

app/views/articles/edit.html.erb
<h1>lets edit this amazing article now</h1>

<%= render 'form' %>

app/views/articles/home.html.erb
<div class="page-header">
  <h1>Welcome to the articles website <small>articles in this website are just FAB </small></h1>
</div>

<br>

<div class="jumbotron">
  <h1>You want to sign up and write, GO AHEAD B##CH</h1>
  <p>...</p>
  <p> <%= link_to :"signup", signup_path ,class: "btn btn-primary btn-lg" %></p>
</div>

app/views/articles/index.html.erb
<h1>Artiles listing</h1>

<div align = "left">
  <%= will_paginate %>

</div>

<% @articles.each do |article| %>

<div class="flex-container">
  <div class="row">
		        <div class="item col-md-offset col-lg-8 col-xs-offset ">
              <div class="well well-lg ">
				          <div class="item-inner rounded center">
					               <div class="icon-holder text-center mx-auto mb-3"></div><!--//icon-holder-->
					                    <div class="articke-title">
                                <%= article.title%>
                              </div>
					                         <div class= "article-body">
                                     <%= simple_format(truncate(article.description, length:60))%>
                                   </div>
					                              <div class="mt-2"> <%= link_to "read more", article_path(article)%></div> <hr>

                                        <%if article.user%>
                                        <small>created by:
                                          <%= article.user.username%>,
                                          <%=article.created_at.strftime("%Y/%m/%d")%>

                                        </small>
                                         <% else %>
                                          <small>created by: user not found , </small>
                                          <%=article.created_at.strftime("%Y/%m/%d")%>
                                          <%end%>
                                              <div class="tags">
                                                <p><%= render article.categories %></p>
                                              </div>
				        </div>  <!--//item-inner-->
			    </div><!--//item-->
        </div>
  </div>
</div>
<%end%>

<div align = "left">
  <%= will_paginate %>

</div>

app/views/articles/new.html.erb
<h3>lets create amazing articles  <span class="label label-default">NOW</span></h3>
<br>
<%= render 'form' %>

app/views/articles/show.html.erb
<h2>Title: <%= @article.title %></h2>
<div class=" col-xs-10 col-xs-offset-1 col-lg-12 col-lg-offset-0 ">
    <h4 class="center"> <strong>full  article</strong> </h4>
      <hr>
              <%= simple_format(@article.description) %>
              <% if logged_in && (current_user == @article.user || current_user.admin?) %>

                  <div class="article-actions">
                        <hr>
                       <%= link_to "back to articles" , articles_path, class:"btn btn-xs btn-success " %>
                       <%= link_to "edit the article" , edit_article_path(@article) , class:"btn btn-xs btn-primary " %>
                       <%= link_to "Delete thevarticle" , article_path(@article),method: :delete, data: {confirm:'are you sure?'},
                                                         class: "btn btn-xs btn-danger" %>
                    </div>
              <%end%>
        <% if @article.categories.any?%>
               <p><%= render @article.categories %></p>
         <%end%>
</div>

app/views/categories/_category.html.erb
<span class="badge"> <%= link_to category.name , category_path(category) %> </span>

app/views/categories/edit.html.erb
<%= render 'shared/errors', obj:@category %>

<div class="row">
  <div class="col-xs-12">
<%= form_for(@category, :html => {class: "form-horizontal", role:'form'}) do |a| %>
<div class="form-group">
  <label class="col-sm-2 control-label">Category name </label>
    <div class="col-sm-8">
        <%= a.text_field :name , class: "form-control", placeholder: 'enter category name' %>
    </div>
</div>
      <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <%= a.submit class: "btn btn-primary btn-lg" %>
          </div>
      </div>
<%end%>
</div>

</div>

app/views/categories/index.html.erb
<h1 align= "center" >here is the list of all categories</h1>

<div align = "left">
  <%= will_paginate %>

</div>

<% @categories.each do |category| %>
<ul class="list-group">
  <li class="list-group-item d-flex justify-content-between align-items-center">
    <%= link_to category.name , category_path(category)%>
    <span class="badge badge-primary badge-pill"><%= category.articles.count %></span>
  </li>
</ul>
<%end%>
<div align = "left">
  <%= will_paginate %>

</div>

app/views/categories/new.html.erb
<%= render 'shared/errors', obj:@category %>

<div class="row">
  <div class="col-xs-12">
<%= form_for(@category, :html => {class: "form-horizontal", role:'form'}) do |a| %>
<div class="form-group">
  <label class="col-sm-2 control-label">Category name </label>
    <div class="col-sm-8">
        <%= a.text_field :name , class: "form-control", placeholder: 'enter category name' %>
    </div>
</div>
      <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <%= a.submit class: "btn btn-primary btn-lg" %>
          </div>
      </div>
<%end%>
</div>

</div>

app/views/categories/show.html.erb
<h1>Artiles listing for Category : <%= @category.name %></h1>

<div align = "center">
  <%= will_paginate @article_categories %>
</div>
<% @article_categories.each do |article| %>
<div class="flex-container">
  <div class="row">
		        <div class="item col-md-offset col-lg-8 col-xs-offset ">
              <div class="well well-lg ">
				          <div class="item-inner rounded center">
					               <div class="icon-holder text-center mx-auto mb-3"></div><!--//icon-holder-->
					                    <div class="articke-title">
                                <%= article.title%>
                              </div>
					                         <div class= "article-body">
                                     <%= simple_format(truncate(article.description, length:60))%>
                                   </div>
					                              <div class="mt-2"> <%= link_to "read more", article_path(article)%></div> <hr>

                                        <%if article.user%>
                                        <small>created by:
                                          <%= article.user.username%>,
                                          <%=article.created_at.strftime("%Y/%m/%d")%>

                                        </small>
                                         <% else %>
                                          <small>created by: user not found , </small>
                                          <%=article.created_at.strftime("%Y/%m/%d")%>
                                          <%end%>
                                              <div class="tags">
                                                <p><%= render article.categories %></p>
                                              </div>
				        </div>  <!--//item-inner-->
			    </div><!--//item-->
        </div>
  </div>
</div>
<%end%>

<div align = "center">
  <%= will_paginate @article_categories %>
</div>

app/views/layouts/_footer.html.erb
  <!-- Footer -->
  <div class="container-fluid">

  <footer class="footer">
  <small>
    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2019 Copyright:
      <a href="https://google.com"> Mytest</a>
    </div>
    <!-- Copyright -->
  </small>
  </footer>
  <!-- Footer -->
  </div>

app/views/layouts/_messages.html.erb
<div class="rows">
  <div class="col-xs-10 col-xs-offset">
    <% flash.each do |name,msg| %>
    <div class='alert alert-<%="#{name}"%> role="alert"'>
      <a herf= "#" class="close" data-dismiss="alert">&#215; </a>
      <%= content_tag :div, msg, :id => "flash #{name}" %>
    </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigator.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'My Blog',root_path,class: "navbar-brand" , id: 'logo' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if logged_in  %>
        <li> <%= link_to 'Create new article', new_article_path, class: "sr-only" , id:'new-link' %> </li>
        <%end%>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" ID = "drop-main" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "All articles", articles_path%></li>
            <li><%= link_to "All Users", users_path%></li>
            <li><%= link_to "All categories", categories_path%></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">feature coming soon<</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">feature coming soon<</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" ID = "drop-main" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% Category.all.each do | category | %>
            <li><%= link_to "#{category.name}", category_path(category)%></li>
              <% end %>
          </ul>

        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <% if current_user %>
      <ul class="nav navbar-nav navbar-right">
        <li> <%= link_to :"logout" , logout_path,method: :delete, data: {confirm:'are you sure?'} %> </li>
        <li><%= link_to "profile", user_path(current_user)  %></li>


      </ul>
      <%else %>
      <ul class="nav navbar-nav navbar-right">
        <li> <%= link_to :"login" , login_path%> </li>
        <li><%= link_to "signup", signup_path  %></li>

     <%end%>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mytest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%# stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>

  <body>

    <%=render 'layouts/navigator'%>
    <%=render 'layouts/messages'%>

    <div class="container">
      <%= yield %>

   </div>
   <%=render'layouts/footer'%>
   <%= debug(params) if Rails.env.development? %>


  </body>
</html>

app/views/seassions/new.html.erb
<h1 align = "center" ></h1>



<%= form_for(:seassion, :html => {class: "form-horizontal", role:'form'}, url: login_path) do |a| %>

  <div class="form-group">
    <label class="col-sm-2 control-label">Email</label>
      <div class="col-sm-8">
          <%= a.email_field :email,class: "form-control", placeholder: 'enter email' %>
      </div>
 </div>
 <div class="form-group">
   <label class="col-sm-2 control-label">password</label>
     <div class="col-sm-8">
         <%= a.password_field  :password ,class: "form-control", placeholder: 'enter  password' %>
     </div>
</div>
      <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <%= a.submit "login" , class: "btn btn-primary btn-lg" %>
          </div>
      </div>
<%end%>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="alert alert-danger" role="alert" >
       <h2><%= pluralize(obj.errors.count, "error") %> prohibited this article from being saved:</h2>
       <ul>
         <% obj.errors.full_messages.each do |msg| %>
           <li> <%= msg %></li>
         <% end %>
       </ul>
    </div>
<% end%>

app/views/users/_form.erb
<%= render 'shared/errors', obj:@user %>

<div class="row">
  <div class="col-xs-12">
<%= form_for(@user, :html => {class: "form-horizontal", role:'form'}) do |a| %>
<div class="form-group">
  <label class="col-sm-2 control-label">User name</label>
    <div class="col-sm-8">
        <%= a.text_field :username , class: "form-control", placeholder: 'enter user name' %>
    </div>
</div>
  <div class="form-group">
    <label class="col-sm-2 control-label">Email</label>
      <div class="col-sm-8">
          <%= a.email_field :email,class: "form-control", placeholder: 'enter  email' %>
      </div>
 </div>
 <div class="form-group">
   <label class="col-sm-2 control-label">password</label>
     <div class="col-sm-8">
         <%= a.password_field  :password ,class: "form-control", placeholder: 'enter  password' %>
     </div>
</div>
      <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <%= a.submit name: button_name , class: "btn btn-primary btn-lg" %>
          </div>
      </div>
<%end%>
</div>

</div>

app/views/users/edit.html.erb
<%= render 'form', button_name:'update' %>

app/views/users/index.html.erb
<h1 align= "center" >here is the list of all users signed up</h1>
<% @users.each do |user| %>
<div align= "center">
  <ul class = "listing">
    <div class="rows">
      <div class="well col-md-4 col-md-offset-1">
        <li>created at: <%=user.created_at.strftime("%Y/%m/%d")%></li>
        <div class="prof-image" ><%= image_tag avatar_url(user,105)%></div>
        <li><%=link_to user.username, user_path(user)%></li>
        <li><%=pluralize(user.articles.count,"article") if user.articles %></li>
      </div>
    </div>
  </ul>
  </div>
<%end%>

app/views/users/login.html.erb
<h1 align = center> login in baby</h1>

app/views/users/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-sm-2 col-md-2">
            <%= image_tag avatar_url(@user, 150) %>
        </div>
        <div class="col-sm-4 col-md-4">
            <blockquote>
                <p><%= @user.username%></p> <small><cite title="Source Title">Riyadh, Saudi Arabia  <i class="glyphicon glyphicon-map-marker"></i></cite></small>
            </blockquote>
            <p> <i class="glyphicon glyphicon-envelope"></i> <%= @user.email%><br
                /> <i class="glyphicon glyphicon-globe"></i> www.bootsnipp.com
                <br /> <i class="glyphicon glyphicon-gift"></i> <%= @user.created_at.strftime("%Y/%m/%d")%></p>
        </div>
             <% if logged_in && current_user.admin? %>
        <div align = "center">
          <%= link_to "Delete user" , user_path(@user), method: :delete, data:{confirm: " are you sure you want to delete user?"}, class:"btn btn-xs btn-success " %>
        </div>
        <%end%>
      </div>
    </div>

      <hr>
      <h3>articles related to <%= @user.username%> :</h3>
      <% if @user.articles.none? %>
      <h2>Sorry, this user has no articles yet . . . </h2>
      <% else %>
      <%@user.articles.each do |article| %>

          <div class="item-inner rounded center col-lg-8 col-xs-10 offset-1 ">
            <div class="well well-lg ">
                      <div class="articke-title">
                        <%= article.title%>
                      </div>
                           <div class= "article-body">
                             <%= simple_format(truncate(article.description, length:60))%>
                           </div>
                                <div class="mt-2"> <%= link_to "read more", article_path(article)%></div>
                                  <%=article.created_at.strftime("%Y/%m/%d")%>
                                  <% if current_user.admin %>
                                  <div class="article-actions">
                                    <hr>
                                    <%= link_to "back to articles" , articles_path, class:"btn btn-xs btn-success " %>
                                    <%= link_to "edit the article" , edit_article_path(article) , class:"btn btn-xs btn-primary " %>
                                    <%= link_to "Delete thevarticle" , article_path(article),method: :delete, data: {confirm:'are you sure?'},
                                                                      class: "btn btn-xs btn-danger" %>
                                </div>
                                <%end%>
        </div>  <!--//item-inner-->
</div>

<%end%>
<%end%>

app/views/welcome/about.html.erb
<<h2>about</h2>

app/views/welcome/home.html.erb
<<h1>this webcccsite is for my baby </h1>